png("plot3.png", width = 480, height = 480)
plot(df$Date_Time, df$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(df$Date_Time, df$Sub_metering_2, col="red")
lines(df$Date_Time, df$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), cex=1.2, y.intersp=0.8, pch="-", lty=1,lwd=2.5)
dev.off()
